Fix deinstallation of stale ports
It's mostly a hack, it should be replaced by pkg autoremove as soon as
it works.

diff --git a/ports/portmaster.patch b/ports/portmaster.patch
--- a/ports/portmaster.patch
+++ b/ports/portmaster.patch
@@ -1,5 +1,5 @@
 --- portmaster.orig	2012-01-27 19:10:47.000000000 +0100
-+++ portmaster	2012-01-31 02:28:07.181096526 +0100
++++ portmaster	2012-01-31 03:07:29.361097824 +0100
 @@ -292,7 +292,13 @@
  			 unset -v PM_URB_LIST;
  			 $PM_SU_CMD /usr/bin/nice /usr/bin/make $PM_MAKE_ARGS $*; ); }
@@ -383,33 +383,73 @@
  
  	echo '' ; echo "===>>> Running ${0##*/} -s $ARGS"
  	exec $0 -s $ARGS
-@@ -2075,7 +2195,11 @@
+@@ -2069,13 +2189,22 @@
+ if [ -n "$CLEAN_STALE" ]; then
+ 	[ -z "$no_del_list" ] && export no_del_list=':'
+ 
+-	for file in `find $pdb -type f -name \+REQUIRED_BY -empty` ; do
++	#TODO: will use pkg autoremove when it works
++	if [ -z "$use_pkgng" ]; then
++		find_stale_ports="find $pdb -type f -name \+REQUIRED_BY -empty"
++	else
++		find_stale_ports="pkg query -a \"%?r %n-%v\" | awk '/^0/ { print \$2 }'"
++	fi
++	for file in `eval $find_stale_ports` ; do
+ 		iport="${file%/+REQUIRED_BY}" ; iport=${iport#$pdb/}
+ 
  		case "$no_del_list" in *:${iport}:*) continue ;; esac
  
  		origin=`origin_from_pdb $iport`
 -		deplist=`grep -l DEPORIGIN:$origin$ $pdb/*/+CONTENTS`
++		deplist=""
 +		if [ -z "$use_pkgng" ]; then
 +			deplist=`grep -l DEPORIGIN:$origin$ $pdb/*/+CONTENTS`
-+		else
-+			deplist=`pkg query "%rn-%rv" $origin`
 +		fi
  		if [ -n "$deplist" ]; then
  			echo ''
  			echo "===>>> Warning: Unrecorded dependencies on ${iport}:"
-@@ -2088,7 +2212,11 @@
+@@ -2088,22 +2217,32 @@
  			continue
  		fi
  
 -		pkg_info $iport
 +		if [ -z "$use_pkgng" ]; then
 +			pkg_info $iport
++			pkg_delete="pkg_delete"
 +		else
 +			pkg info -f $iport
++			pkg_delete="pkg delete"
 +		fi
  
  		get_answer_yn n "\t===>>> ${iport} is no longer depended on, delete"
  		case "$?" in
-@@ -2243,7 +2371,12 @@
+ 		0)	[ -n "$BACKUP" ] && { init_packages ; pm_pkg_create $pbu $iport; }
+ 			[ -z "$DONT_SCRUB_DISTFILES" ] && { delete_all_distfiles $origin; delete_dist_list; }
+ 
+-			echo "===>>> Running pkg_delete -f $iport"
+-			pm_pkg_delete_s -f $iport || fail 'pkg_delete failed'
++			echo "===>>> Running $pkg_delete -f $iport"
++			pm_pkg_delete_s -f $iport || fail "$pkg_delete failed"
+ 
+ 			exec $0 -s $ARGS ;;
+-		*)	get_answer_yn n "\t===>>> Delete this dependency data"
+-			case "$?" in
+-			0)	pm_unlink_s $file ;;
+-			*)	no_del_list="${no_del_list}${iport}:" ;;
+-			esac ;;
++		*)	if [ -z "$use_pkgng" ]; then
++				get_answer_yn n "\t===>>> Delete this dependency data"
++				case "$?" in
++				0)	pm_unlink_s $file ;;
++				*)	no_del_list="${no_del_list}${iport}:" ;;
++				esac
++			else
++				no_del_list="${no_del_list}${iport}:"
++			fi ;;
+ 		esac
+ 	done
+ 	exit 0
+@@ -2243,7 +2382,12 @@
  			fail "No entry for $origin in $PM_INDEX"
  	fi
  
@@ -423,7 +463,7 @@
  	\<)	build_l="${build_l}\tUpgrade $iport to $new_port\n" ;;
  	=)	build_l="${build_l}\tRe-install $iport\n" ;;
  	\>)	build_l="${build_l}\tDowngrade $iport to $new_port\n" ;;
-@@ -2466,7 +2599,11 @@
+@@ -2466,7 +2610,11 @@
  				fail "Cannot cd to $d_port"
  			fi
  			for glob in $conflicts; do
@@ -436,7 +476,7 @@
  				if [ -n "$confl_p" ]; then
  					confl_p=${confl_p%% *}
  					echo ''
-@@ -2601,6 +2738,10 @@
+@@ -2601,6 +2749,10 @@
  		done
  
  		for dep in $build_only_dl_g; do
@@ -447,7 +487,7 @@
  			grep -q "@comment DEPORIGIN:${dep#$pd/}$" $pdb/*/+CONTENTS ||
  				temp_bodlg="$temp_bodlg $dep"
  		done
-@@ -2635,7 +2776,14 @@
+@@ -2635,7 +2787,14 @@
  	echo "===>>> Begin $verb ports that depend on $PM_URB_IPORTS"
  	echo ''
  
@@ -462,7 +502,7 @@
  		for req_by in `grep -l DEPORIGIN:${origin}$ $pdb/*/+CONTENTS`; do
  			req_by="${req_by%/+CONTENTS}"
  			req_by="${req_by##*/}"
-@@ -2806,9 +2954,16 @@
+@@ -2806,9 +2965,16 @@
  		*/*)	origin=$port ;;
  		*)	# If an installed version does not exist at this
  			# point it probably got updated as a dependency
@@ -482,7 +522,7 @@
  			fi
  			origin=`origin_from_pdb $port` ;;
  		esac
-@@ -3036,7 +3191,12 @@
+@@ -3036,7 +3202,12 @@
  	/*)	echo '' ; no_valid_port ;;
  	*/*)	portdir=$argv ;;
  	\.)	portdir=${PWD##*/ports/} ;; # Not always $pd, could be symlink
@@ -496,7 +536,7 @@
  	esac
  
  	if [ -z "$portdir" -a -z "$upg_port" ]; then
-@@ -3069,11 +3229,20 @@
+@@ -3069,11 +3240,20 @@
  
  	case "$arg2" in
  	*/*)	ro_opd=$arg2 ; ro_upg_port=`iport_from_origin $ro_opd` ;;
@@ -521,7 +561,7 @@
  		fi
  		[ -n "$ro_upg_port" ] && ro_opd=`origin_from_pdb $ro_upg_port`
  	esac
-@@ -3525,7 +3694,12 @@
+@@ -3525,7 +3705,12 @@
  		pm_v "===>>> Available package ($latest_pv) matches the current version"
  	elif [ -n "$latest_pv" -a -n "$PM_PACKAGES_NEWER" ]; then
  		if [ -n "$upg_port" ]; then
@@ -535,7 +575,7 @@
  			\<)	use_package=up_newer
  				pm_v "===>>> Available package ($latest_pv)"
  				pm_v "       is newer than installed ($upg_port)" ;;
-@@ -3541,7 +3715,12 @@
+@@ -3541,7 +3726,12 @@
  			pm_v "===>>> There is a package available ($latest_pv)"
  		fi
  	elif [ -n "$latest_pv" ]; then
@@ -549,7 +589,7 @@
  		\<)	# Could happen if ports tree is out of date
  			use_package=up_old_tree
  			pm_v "===>>> Available package ($latest_pv)"
-@@ -3640,7 +3819,12 @@
+@@ -3640,7 +3830,12 @@
  		    grep -v ^$LOCALBASE_COMPAT > $ldconfig_out
  
  		unset temp
@@ -563,7 +603,7 @@
  		    sort - $ldconfig_out | uniq -d`; do
  			temp="${temp}$file "
  		done
-@@ -3743,29 +3927,32 @@
+@@ -3743,29 +3938,32 @@
  	fi
  fi
  
@@ -619,7 +659,7 @@
  if [ -n "$preserve_dir" ]; then
  	rmdir $preserve_dir 2>/dev/null
  	unset preserve_dir preserve_port_files
-@@ -3781,7 +3968,12 @@
+@@ -3781,7 +3979,12 @@
  temp=`find $LOCALBASE_COMPAT -type d -empty 2>/dev/null`
  if [ -z "$temp" ] && [ -d "$LOCALBASE_COMPAT" ]; then
  	unset files
@@ -633,7 +673,7 @@
  		[ -f "${LOCALBASE_COMPAT}/${file##*/}" ] &&
  			files="${files}${LOCALBASE_COMPAT}/${file##*/} "
  	done
-@@ -3844,7 +4036,8 @@
+@@ -3844,7 +4047,8 @@
  	/bin/unlink $dist_list_temp ; unset ds dist_list_temp
  fi
  
@@ -643,7 +683,7 @@
  	if grep -q DEPORIGIN $pdb/$new_port/+CONTENTS; then
  		echo "===>>> Updating dependencies for $new_port to match installed versions"
  		update_contents $pdb/$new_port/+CONTENTS
-@@ -3879,27 +4072,29 @@
+@@ -3879,27 +4083,29 @@
  	echo ''
  fi
  
